 os: osx
 osx_image: xcode11.2
 language: swift
 script: xcodebuild clean build -workspace DarkMode\ Demo.xcworkspace -scheme "DarkMode Demo" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
